name: Build Releases

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} ${{ matrix.addon }} add-on
    strategy:
      matrix:
        addon: [ "addon-stable", "addon-testing" ]
        arch: ["aarch64", "amd64", "i386"]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get version to build
        if: ${{ github.event_name == 'release' }}
        run: |
          VERSION=$(grep 'version: ' ./${{ matrix.addon }}/config.yaml | sed -e 's/^version: //')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Prepare ${{ matrix.addon }} build
        if: ${{ github.ref_name == env.VERSION }}
        run: |
          cp -a dao/* ${{ matrix.addon }}

      - name: Build ${{ matrix.addon }} add-on
        if: ${{ github.ref_name == env.VERSION }}
        uses: home-assistant/builder@2025.03.0
        with:
          args: |
            --generic $VERSION \
            --${{ matrix.arch }} \
            --image "dao-${{ matrix.arch }}" \
            --target ${{ matrix.addon }} \
            --version $VERSION \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon