name: Build Releases

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} ${{ matrix.addon }} addon
    strategy:
      matrix:
        addon: [ "stable", "testing" ]
        arch: [ "aarch64", "amd64", "i386" ]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get version to build
        if: ${{ github.event_name == 'release' }}
        run: |
          VERSION=$(grep 'version: ' ./addon-${{ matrix.addon }}/config.yaml | sed -e 's/^version: //')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set stable or testing on release
        if: ${{ github.ref_name == env.VERSION }}
        shell: bash
        run: |
          if [[ ${{ matrix.addon }} == "stable" ]]; then
            echo "this is a final release, setting stable tag"
            echo "LATEST=" >> $GITHUB_ENV;
            echo "EXTRA_TAG=--additional-tag stable" >> $GITHUB_ENV
          else
            echo "this is a release candidate, not setting stable or latest tag"
            echo "LATEST=--no-latest" >> $GITHUB_ENV;
            echo "EXTRA_TAG=--additional-tag testing" >> $GITHUB_ENV;
          fi 

      - name: Login to GHCR
        if: ${{ github.ref_name == env.VERSION }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Prepare ${{ matrix.addon }} build
        if: ${{ github.ref_name == env.VERSION }}
        run: |
          cp -a dao/* ./addon-${{ matrix.addon }}

      - name: Build ${{ matrix.addon }} add-on
        if: ${{ github.ref_name == env.VERSION }}
        uses: home-assistant/builder@2025.03.0
        with:
          args: |
            --generic $VERSION \
            --${{ matrix.arch }} \
            --image "dao-${{ matrix.arch }}" \
            --target addon-${{ matrix.addon }} \
            --version $VERSION \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            ${{ env.LATEST }} \
            ${{ env.EXTRA_TAG }} \
            --addon