name: Test Builder

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} ${{ matrix.addon }} add-on
    strategy:
      matrix:
        addon: [ "addon-testing"]
        arch: [ "amd64" ]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get version to build
        run: |
          VERSION=$(grep version ./${{ matrix.addon }}/config.yaml | sed -e 's/^version: //')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Prepare ${{ matrix.addon }} build
        run: |
          cp -a dao/* ${{ matrix.addon }}

      - name: Test ${{ matrix.addon }} add-on
        if: steps.check.outputs.build_arch == 'true'
        uses: home-assistant/builder@2025.03.0
        with:
          args: |
            --test \
            --generic $VERSION \
            --${{ matrix.arch }} \
            --image "${{ steps.check.outputs.image }}" \
            --target ${{ matrix.addon }} \
            --version $VERSION \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon
